Module1/Module1/Models/ErrorViewModel.cs
using System;

namespace Module1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Module1/Module1/Models/File.cs
using System.ComponentModel.DataAnnotations;

namespace Module1.Models
{
    public class File
    {
        public int Id { get; set; }        
        public string OriginName { get; set; }
        public int DownloadCount { get; set; }     
        public string Link { get; set; }        
        public string Password { get; set; }
        
        public int Count { get; set; }
        public string Name { get; set; }       
        public string Path { get; set; }       
        public string Content { get; set; }       
        public string ContentType { get; set; }       
        public string Description { get; set; }
    }
}

Module1/Module1/Controllers/FileController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Module1.Data;
using File = Module1.Models.File;

namespace Module1.Controllers
{
    public class FileController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IHostingEnvironment _appEnvironment;

        public FileController(DatabaseContext context, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }
        public IActionResult Index()
        {
            return View(_context.Files);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(IFormFile formFile, string name, string description, string link, string password, int count)
        {
            if (!ModelState.IsValid || count < 0)
                return View();
            var file = new File();
            if (formFile != null && formFile.Length > 0)
            {
                file.Name = name == null ? formFile.FileName : name;
                file.OriginName = formFile.FileName;
                file.Description = description;
                if (link != null && !link.Equals(string.Empty))
                {
                    if (_context.Files.FirstOrDefault(c => c.Link == link) == default(File))
                        file.Link = link;
                    else
                    {
                        ModelState.AddModelError("", "Link should be unique");
                        return View();
                    }
                }
                else file.Link = GetLink(file.OriginName);
                if (password != null)
                    file.Password = password;
                var filePath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files"));
                using (var fileStream = new FileStream(Path.Combine(filePath, file.OriginName), FileMode.Create))
                    formFile.CopyTo(fileStream);
                file.Path = "wwwroot/Files/"+ file.OriginName;
                file.ContentType = formFile.ContentType;
                var readStream = formFile.OpenReadStream();
                byte[] bytes = new byte[readStream.Length];                
                readStream.Read(bytes, 0, Convert.ToInt32(readStream.Length));
                var strBase64 = Convert.ToBase64String(bytes);
                var content = string.Format("data:" + file.ContentType + ";base64,{0}", strBase64);
                file.Content = content;
                file.Count = count;
                _context.Files.Add(file);
                _context.SaveChanges();
                return RedirectToAction("Index");
                
            }

            return View();

        }

        private string GetLink(string chars)
        {
            var random = new Random();
            var builder = new StringBuilder();
            builder.Append("https://");
            for (int i = 0; i < 6; i++)
            {
                var pos = random.Next(0, chars.Length - 1);
                builder.Append(chars[pos]);
            }

            return builder.ToString();
        }

       
        public IActionResult Show(int id)
        {
            return View(_context.Files.First(f => f.Id == id));
        }

        public IActionResult GetFile(int id)
        {
            var file = _context.Files.FirstOrDefault(f => f.Id == id);
            string file_path = Path.Combine(_appEnvironment.ContentRootPath, file.Path);
            string file_type = file.ContentType;
            file.DownloadCount++;
            file.Count--;
            _context.SaveChanges();
            return PhysicalFile(file_path, file_type, file.OriginName);
        }
        
        [HttpPost]
        public IActionResult GetFileByPassword(int id, string password)
        {
            if (_context.Files.FirstOrDefault(f => f.Id == id && f.Password == password) == default(File))
                return RedirectToAction("Index");
            return GetFile(id);
        }
    }
}

Module1/Module1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Module1.Models;

namespace Module1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Module1/Module1/Views/File/Create.cshtml
@model Module1.Models.File

@using (Html.BeginForm("Create", "File", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    <div class="buttons-block">
        <input type="file" class="form-control-file" name="formFile">
    </div>
    <div>
        <h1>Name</h1>
        <input type="text" name="name"/>
    </div>
    <div>
        <h1>Description</h1>
        <textarea name="description"></textarea>
    </div>
    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h1>File link</h1>
        <input type="text" name="link"/>
    </div>
    <div>
        <h1>File password</h1>
        <input type="text" name="password"/>
    </div>
    <div>
        <h1>Download count</h1>
        <input type="number" name="count"/>
    </div>
    <div class="buttons-block">
        <input type="submit" class="btn btn-primary" value="Add"/>
    </div>
}

Module1/Module1/Views/File/Index.cshtml
@model IEnumerable<Module1.Models.File>

@foreach (var file in Model)
{
   <h3>@file.Name</h3>
   <a href="~/File/Show/@file.Id">Show</a>
}

Module1/Module1/Views/File/Show.cshtml
@model Module1.Models.File

<h3>File name: @Model.Name</h3>
<h6>Description: @Model.Description</h6>
<h6>Origin name: @Model.OriginName</h6>
<h6>Downloads: @Model.DownloadCount</h6>

@if (Model.Count <= 0)
{
    <h6>Sorry, you can't download this file</h6>
}
else if (Model.Password != null)
{
    using (Html.BeginForm("GetFileByPassword", "File", FormMethod.Post))
    {
        <input type="hidden" name="id" value="@Model.Id"/>
        <h6>Download by password</h6>
        <input type="text" name="password"/>
        <input type="submit" value="Send"/>
    }
}
else
{
    <h6>Download file</h6>
    <a href="~/File/GetFile/@Model.Id">@Model.Link</a>
}
<div>
    <object data=@Model.Content type=@Model.ContentType></object>
</div>

Module1/Module1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div>
        <a href="~/File/Create">Create new file</a>
    </div>
    <div>
        <a href="~/File/Index">Show all files</a>
    </div>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Module1/Module1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Module1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Module1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Module1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>